### PR TITLE
Update WebSocketJs.hx

### LINKED ISSUE #7: nodejs target is not supported
Because `#if js` falls into `WebSocketJs` which relies on `js.html.WebSocket` that does not exist in nodejs environment.

### PR DESCRIPTION
**Pull request by serjek**
Adding nodejs support, fixes #7

### CODE REVIEW

**Comment by endel** [comment]
Interesting, thanks a lot for the PR @serjek! Out of curiosity, what is this importing? 👀 

```
@:jsRequire('websocket', 'w3cwebsocket')
```

Are there more configuration and/or node module required to install to make this work with Node?

**Comment by serjek** [comment]
Hey @endel yes basically it will compile into `require('websocket').w3cwebsocket` which I discovered [here](https://github.com/theturtle32/WebSocket-Node) while I was looking for a way to patch a problem.

I guess it is worth adding a comment that `websocket` module is required but on the other hand brave people who would use nodejs + colyseus-hx will figure this out anyway from error message (i hope) 😅

But yeah I will add a comment anyway.

**Comment by endel** [comment]
I see! Thanks for clarifying. We can probably use the `ws` instead, then? (it is the most well-maintaned websocket client/server for Node.js out there) https://github.com/websockets/ws

Would this work??

```
@:jsRequire('ws')
```

**Comment by serjek** [comment]
Unfortunately I didn't find w3c socket spec support in `ws`, this is why I had to look for alternatives. w3c spec is required to fully reuse `WebSocketJs` implementation. I'd have to create a full featured `WebSocketNodeJs` impl to be able to use `ws` which I would like to avoid due to time pressure ;)

**Pull request merged**
